import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import ToasterWrapper from "@/components/Toaster/ToasterWrapper";
import { StoreProvider } from "@/lib/StoreProvider";

const poppinss = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const circularStd = localFont({
  src: "./fonts/CircularStd-Book.ttf",
  variable: "--font-circularStd",
});

export const metadata: Metadata = {
  title: "SolveMyAllergies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinss.variable} ${circularStd.variable}`}
      >
        <StoreProvider>
          <ToasterWrapper>
            {children}
          </ToasterWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
